pipeline {
    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build React') {
            steps {
                sh '''
                    docker run --rm \
                    -v $PWD:/app \
                    -w /app \
                    node:22-alpine \
                    sh -c "node -v && npm -v && npm install && npm run build"
                '''
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '**/dist/**/*', allowEmptyArchive: true
        }
        failure {
            echo "Pipeline failed"
        }
    }
}