pipeline {
    agent any
    options {
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install & Build') {
            steps {
                dir('my-reat-app') {
                    sh '''
                        echo "Đang đứng tại thư mục: $PWD"
                        # Kiểm tra xem Node đã có sẵn chưa
                        node -v
                        npm -v
                        
                        # Chạy trực tiếp, không dùng lệnh docker run
                        npm ci
                        npm run build
                    '''
                }
            }
        }
    }
    post {
        success {
            // Khi lưu Artifact, đường dẫn phải tính từ thư mục gốc của Git
            archiveArtifacts artifacts: 'my-reat-app/dist/**/*', fingerprint: true, allowEmptyArchive: true
        }
        failure {
            echo 'Pipeline thất bại'
        }
    }
}